Implement sync for multi ig node pool
panslava/ingress-gce pull request #4
Opened 2022-01-24 18:31 UTC by panslava

2022-01-25 09:29 UTC, kl52752 requested changes

2022-01-25 09:29 UTC, kl52752 commented on pkg/instancegroup/multiigcontroller.go
> +func (igc *MultiIGController) getSuffixedIgNameByIndex(index int) string {
I think that getIgNameByIndex is better name

2022-01-25 09:29 UTC, kl52752 commented on pkg/instancegroup/multiigcontroller.go
> +		availableSize := maxIgSize - igSizes[currentIgName]
you can just use F.MaxIgSize it is exported

2022-01-25 09:49 UTC, kl52752 commented on pkg/instancegroup/multiigcontroller.go
> +func (igc *MultiIGController) getSuffixedIgNameByIndex(index int) string {
What do you think of creating new namer just like for L4? I don't think that this function belongs to controller.

2022-01-25 12:41 UTC, panslava commented on pkg/instancegroup/multiigcontroller.go
> +func (igc *MultiIGController) getSuffixedIgNameByIndex(index int) string {
Added function to an old namer

2022-01-25 12:41 UTC, panslava commented on pkg/instancegroup/multiigcontroller.go
> +		availableSize := maxIgSize - igSizes[currentIgName]
Done

2022-01-25 13:58 UTC, kl52752 commented on pkg/utils/namer/namer.go
> +func (n *Namer) InstanceGroupByIndex(index int) string {
Can you extract it to separate PR (with unit tests) ?

2022-01-25 13:58 UTC, kl52752 commented on pkg/utils/namer/namer.go
> +	} else {
else if not necessary just return value

2022-01-25 15:32 UTC, panslava commented on pkg/utils/namer/namer.go
> +	} else {
fixed

2022-02-02 16:52 UTC, cezarygerard commented on pkg/instancegroup/multiigcontroller.go
> +	return igc.instancePool.Sync(allNodeNames)
why calling this?

the
"func (igc *MultiIGController) sync(key string) error "

replaces instancePool.Sync

2022-02-02 16:52 UTC, cezarygerard commented on pkg/instancegroup/multiigcontroller.go
> +	allNodeNames, err := utils.GetReadyNodeNames(listers.NewNodeLister(igc.lister))
NodeLister should be a field in MultiIGController
instead of igc.lister

2023-12-21 06:52 UTC, closed without merging